on:
  push:
    branches:
      - master

# on:
#   push:
#     branches:
#       - master

jobs:
  windows-lib:
    # name: release-mac_x86_64
    runs-on:  windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: cargo build --release
      - name: list 
        run: ls .\target\release
      - uses: actions/upload-artifact@v2
        with:
          name: windows-release
          path: target/release/rustypipeuinative.dll
  android-lib:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r22b
          add-to-path: true
      - name: Install Rustup Android toolchains
        run: rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android
      - name: Install Cargo Make
        run: cargo install cargo-make
      - name: Build project
        run: cargo make --profile release android
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - uses: actions/upload-artifact@v2
        with:
          name: android-release-jnilibs
          path: packages/rustypipeuinative/android/src/main/jniLibs

